version: '3'
services: 
  smartwallet-db:
    image: bitnami/postgresql:latest
    container_name: smartwallet-db
    environment:
      POSTGRES_USER: smartwallet
      POSTGRES_PASSWORD: smartwallet
      POSTGRES_DB: smartwallet
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data